### ISSUE TITLE
什么是闭合的 ast？

### ISSUE THREAD

**Issue by xiaoxiangmoe** [xiaoxiangmoe/pfpl-questions#4]
see 1.1 Abstract Syntax Trees

> When there are no variables, there are no assumptions, and the proof of P is a proof that Q holds for all closed ast’s.

这和 [闭包](https://zh.wikipedia.org/wiki/%E9%97%AD%E5%8C%85_(%E6%95%B0%E5%AD%A6)) 中说的闭合的集合，闭合的运算有什么关系？也就是对哪些运算闭合？

**Comment by MarisaKirisame** [comment]
没关系
这说的是一个AST不依赖于任何自由变量。
